### ISSUE TITLE
where is https://github.com/goki/grid

### ISSUE THREAD

**Issue by ddkwork** [cogentcore/cogent#315]
### Describe the feature

see title

**Comment by kkoreilly** [comment]
It is now in the [vector](https://github.com/cogentcore/cogent/tree/main/vector) directory. We are currently in the process of updating it to all of the new changes in Cogent Core, and it is not working yet, but it will soon.

**Comment by ddkwork** [comment]
Ok





---Original---
From: ***@***.***&gt;
Date: Sat, Feb 24, 2024 12:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogentcore/cogent] where is https://github.com/goki/grid (Issue#315)




 
It is now in the vector directory. We are currently in the process of updating it to all of the new changes in Cogent Core, and it is not working yet, but it will soon.

**Comment by ddkwork** [comment]
> It is now in the [vector](https://github.com/cogentcore/cogent/tree/main/vector) directory. We are currently in the process of updating it to all of the new changes in Cogent Core, and it is not working yet, but it will soon.

![{F7C0FC5C-CD1D-484c-9CCD-F11C37B43F8C}.png](https://github.com/cogentcore/cogent/assets/19886504/5dd49245-39e5-4058-9bf1-6f18567695b7)

Can i make a pr?

**Comment by kkoreilly** [comment]
I am currently working on vector and am getting it working, so you should not do a PR. I appreciate the offer, though.

**Comment by ddkwork** [comment]
Okay



---Original---
From: ***@***.***&gt;
Date: Sun, Feb 25, 2024 14:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cogentcore/cogent] where is https://github.com/goki/grid (Issue#315)




 
I am currently working on vector and am getting it working, so you should not do a PR. I appreciate the offer, though.
